### ISSUE TITLE
Crash when selecting a network to connect

### ISSUE THREAD

**Issue by xek** [pacien/tincapp#11]
The application is stopped after I select a network to connect, here are the logs from adb logcat:

```
D/hwcomposer(  239): void android::intel::DisplayAnalyzer::handleIdleExitEvent(): handling idle exit event
I/ActivityManager( 1575): START u0 {flg=0x10000000 cmp=org.pacien.tincapp/.activities.PromptActivity (has extras)} from uid 10347 on display 0
D/wpa_supplicant( 5074): wlan0: Control interface command 'SIGNAL_POLL'
D/WifiWatchdogStateMachine( 1575): RSSI current: 4 new: -44, 4
D/WindowManager( 1575): adjustConfigurationLw, config:{0 1.0 ?mcc?mnc ?locale ?layoutDir sw360dp w360dp h615dp 480dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:true config.hardKeyboardHidden:2
V/Monotype(28354): SetAppTypeFace- try to flip, app = org.pacien.tincapp
V/Monotype(28354):     Typeface getFontPathFlipFont - systemFont = default#default
I/art     (28354): Rejecting re-init on previously-failed class java.lang.Class<org.apache.commons.a.r>
I/art     (28354): Rejecting re-init on previously-failed class java.lang.Class<org.apache.commons.a.r>
I/art     (28354): Rejecting re-init on previously-failed class java.lang.Class<org.apache.commons.a.r>
I/art     (28354): Rejecting re-init on previously-failed class java.lang.Class<org.apache.commons.a.r>
I/art     (28354): Rejecting re-init on previously-failed class java.lang.Class<org.apache.commons.a.r>
I/dispmgr ( 1282): waiting for message from kernel.
I/dispmgr ( 1282): message from kernel received.
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 level is 3
D/AndroidRuntime(28354): Shutting down VM
E/AndroidRuntime(28354): FATAL EXCEPTION: main
E/AndroidRuntime(28354): Process: org.pacien.tincapp, PID: 28354
E/AndroidRuntime(28354): java.lang.RuntimeException: Unable to start service org.pacien.tincapp.service.TincVpnService@299e6b9f with Intent { cmp=org.pacien.tincapp/.service.TincVpnService (has extras) }: org.apache.commons.c.e.a: Could not locate: org.apache.commons.c.g.l@2caa113e[fileName=network.conf,basePath=/storage/emulated/0/Android/data/org.pacien.tincapp/files/f2f,sourceURL=,encoding=ISO-8859-1,fileSystem=<null>,locationStrategy=<null>]
E/AndroidRuntime(28354): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2908)
E/AndroidRuntime(28354): 	at android.app.ActivityThread.access$2100(ActivityThread.java:147)
E/AndroidRuntime(28354): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
E/AndroidRuntime(28354): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(28354): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(28354): 	at android.app.ActivityThread.main(ActivityThread.java:5264)
E/AndroidRuntime(28354): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28354): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28354): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
E/AndroidRuntime(28354): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
E/AndroidRuntime(28354): Caused by: org.apache.commons.c.e.a: Could not locate: org.apache.commons.c.g.l@2caa113e[fileName=network.conf,basePath=/storage/emulated/0/Android/data/org.pacien.tincapp/files/f2f,sourceURL=,encoding=ISO-8859-1,fileSystem=<null>,locationStrategy=<null>]
E/AndroidRuntime(28354): 	at org.apache.commons.c.g.n.f(Unknown Source)
E/AndroidRuntime(28354): 	at org.apache.commons.c.g.h.b(Unknown Source)
E/AndroidRuntime(28354): 	at org.apache.commons.c.g.h.f(Unknown Source)
E/AndroidRuntime(28354): 	at org.apache.commons.c.b.m.a(Unknown Source)
E/AndroidRuntime(28354): 	at org.apache.commons.c.b.m.a(Unknown Source)
E/AndroidRuntime(28354): 	at org.apache.commons.c.b.m.a(Unknown Source)
E/AndroidRuntime(28354): 	at org.apache.commons.c.b.c.d(Unknown Source)
E/AndroidRuntime(28354): 	at org.apache.commons.c.b.c.c(Unknown Source)
E/AndroidRuntime(28354): 	at org.apache.commons.c.b.a.a.b(Unknown Source)
E/AndroidRuntime(28354): 	at org.pacien.tincapp.service.b.<init>(Unknown Source)
E/AndroidRuntime(28354): 	at org.pacien.tincapp.service.TincVpnService.a(Unknown Source)
E/AndroidRuntime(28354): 	at org.pacien.tincapp.service.TincVpnService.onStartCommand(Unknown Source)
E/AndroidRuntime(28354): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2891)
E/AndroidRuntime(28354): 	... 9 more
W/ActivityManager( 1575):   Force finishing activity org.pacien.tincapp/.activities.StartActivity
D/ForegroundUtils( 2328): Foreground changed, PID: 2058 UID: 10017 foreground: true
D/ForegroundUtils( 2328): Foreground UID/PID combinations:
D/ForegroundUtils( 2328): UID: 10017 PID: 2058
D/ForegroundUtils( 2328): UID: 10347 PID: 28354
I/OpenGLRenderer( 1575): Initialized EGL, version 1.4
I/dispmgr ( 1282): waiting for message from kernel.
I/dispmgr ( 1282): message from kernel received.
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 level is 3
I/dispmgr ( 1282): waiting for message from kernel.
I/dispmgr ( 1282): message from kernel received.
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 level is 3
I/dispmgr ( 1282): waiting for message from kernel.
I/dispmgr ( 1282): message from kernel received.
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 level is 3
I/dispmgr ( 1282): waiting for message from kernel.
I/dispmgr ( 1282): message from kernel received.
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 level is 3
W/ActivityManager( 1575): Activity pause timeout for ActivityRecord{2c8dd142 u0 org.pacien.tincapp/.activities.PromptActivity t14603 f}
D/WindowManager( 1575): adjustConfigurationLw, config:{0 1.0 ?mcc?mnc ?locale ?layoutDir sw360dp w360dp h615dp 480dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:true config.hardKeyboardHidden:2
V/ActivityManager( 1575): Displayed ActivityRecord{3823b335 u0 com.asus.launcher/com.android.launcher3.Launcher t14391} Resume. Not First Launch.
I/dispmgr ( 1282): waiting for message from kernel.
I/dispmgr ( 1282): message from kernel received.
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 level is 3
V/Launcher( 2058): [onResume] called
I/Launcher( 2058): Time spent in onResume: 2ms
D/[NotificationManager]( 2058): [isQuickFindTipFinished] finished: true
I/dispmgr ( 1282): waiting for message from kernel.
I/dispmgr ( 1282): message from kernel received.
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 
I/dispmgr ( 1282): DpstAlgorithm_DPST4_5 level is 3
D/[reSortApps]( 2058): reSortApps, (mApps == null) ? false, AppsCustomizeTabHost.sAllAppMode: 0
D/Launcher.Utilities( 2058): isPhone= true
D/Launcher.Utilities( 2058): isPhone= true
D/Launcher.Utilities( 2058): isPhone= true
D/ForegroundUtils( 2328): Foreground changed, PID: 28354 UID: 10347 foreground: false
D/ForegroundUtils( 2328): Foreground UID/PID combinations:
D/ForegroundUtils( 2328): UID: 10017 PID: 2058
D/PowerSaverService( 2556): current package:com.asus.launcher;activity:com.android.launcher3.Launcher

```

It may have something to do with the location of the data folder, the app shows that the configuration is stored in /storage/emulated/0/Android/data/org.pacien.tincapp/files but the directory I found and in which the configuration was generated is /storage/emulated/legacy/Android/data/org.pacien.tincapp/files ("0" replaced with "legacy"). There are no tincd logs in the cache directory.

```
$ adb shell
shell@Z00A:/ $ ls /storage/emulated/                                           
legacy
shell@Z00A:/ $ ls /storage/emulated/0                                          
/storage/emulated/0: No such file or directory
```

**Comment by xek** [comment]
This was on Asus ZenFone 2 (ASUS_Z00AD), Android 5.0.

**Comment by pacien** [comment]
```
% adb shell -- ls /storage/emulated
legacy
% ssh termux-android -- ls /storage/emulated
0
legacy
```
`/storage/emulated/0` is only accessible through Android apps (incl. Termux) but not using the ADB shell.
I will update the documentation regarding this point.

---

```
E/AndroidRuntime(28354): java.lang.RuntimeException: Unable to start service org.pacien.tincapp.service.TincVpnService@299e6b9f with Intent { cmp=org.pacien.tincapp/.service.TincVpnService (has extras) }: org.apache.commons.c.e.a: Could not locate: org.apache.commons.c.g.l@2caa113e[fileName=network.conf,basePath=/storage/emulated/0/Android/data/org.pacien.tincapp/files/f2f,sourceURL=,encoding=ISO-8859-1,fileSystem=<null>,locationStrategy=<null>]
```
It seems that the `network.conf` file is missing in the network's configuration directory.

**Comment by xek** [comment]
Thanks! The tun device is properly created, but I still can't connect... This may be another issue on my side, however it's hard to debug because as far as I know, I need to pass a command line argument or kill -INT the process, which I can't do because I don't have root...
