### ISSUE TITLE
while build gradle 

### ISSUE THREAD

**Issue by waseem-GitHub-Live** [pacien/tincapp#119]
Check your service account configuration. Json credentials cannot specify a Service Account email while PKCS12 credentials must do so.

Caused by: java.lang.IllegalStateException: Check your service account configuration. Json credentials cannot specify a Service Account email while PKCS12 credentials must do so.
	at com.github.triplet.gradle.play.PlayPublisherPlugin$applyInternal$2.execute(PlayPublisherPlugin.kt:224)
	at com.github.triplet.gradle.play.PlayPublisherPlugin$applyInternal$2.execute(PlayPublisherPlugin.kt:33)

**Comment by pacien** [comment]
Quoting waseem-terafort (2023-08-10 09:29:05)
>         at com.github.triplet.gradle.play.PlayPublisherPlugin$applyInternal$2.execute(PlayPublisherPlugin.kt:33)

This comes from the Gradle Play Publisher plugin,
used to update the Google Play Store listing.

If you're only building locally for your own usage,
you can remove `com.github.triplet.play` from `build.gradle`.
The rest should work as expected even without it.
