### ISSUE TITLE
Invalid network configuration: At least one address must be specified.

### ISSUE THREAD

**Issue by kokoko3k** [pacien/tincapp#19]
I am trying to join an existing tinc network via invite url.
tinc seems to have imported the config (i can see that the files are generated in /android/sdcard/Android/data/org.pacien.tincapp/files/tincvpn), but when i try to start it, a message pops up and says:
```
Unable to start tinc
Invalid network configuration
At least one address must be specified
Open manual                     Close
```
Any idea?
Thanks.

-edit-
Just found this:
https://forums.openvpn.net/viewtopic.php?t=22215
and this, line 283
https://android.googlesource.com/platform/frameworks/base/+/d396a44/services/java/com/android/server/connectivity/Vpn.java

It points to a problem with the tun device. (?)
But "openvpn for android" and "andiodine" both work well here; my device is a zenfone 2 ze551ml, running lollipop 5.0.1

```
logcat says:
I/ActivityManager(  766): START u0 {act=org.pacien.tincapp.intent.action.CONNECT dat=tinc:tincvpn flg=0x10000000 cmp=org.pacien.tincapp/.activities.LaunchActivity} from uid 10286 on display 0
D/WindowManager(  766): adjustConfigurationLw, config:{0 0.85 ?mcc?mnc ?locale ?layoutDir sw360dp w360dp h615dp 480dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:true config.hardKeyboardHidden:2
V/Monotype( 3431): SetAppTypeFace- try to flip, app = org.pacien.tincapp
V/Monotype( 3431):     Typeface getFontPathFlipFont - systemFont = /data/data/flipfont/app_fonts/PTSans-Regular#PT Sans
I/Vpn     (  766): Switched from [Legacy VPN] to org.pacien.tincapp
D/Vpn     (  766): setting state=IDLE, reason=prepare
I/org.pacien.tincapp.service.TincVpnService.a( 3431): Starting tinc daemon for network "tincvpn".
I/art     ( 3431): Rejecting re-init on previously-failed class java.lang.Class<org.apache.commons.a.r>
I/art     ( 3431): Rejecting re-init on previously-failed class java.lang.Class<org.apache.commons.a.r>
I/dispmgr (  318): waiting for message from kernel.
I/dispmgr (  318): message from kernel received.
I/dispmgr (  318): DpstAlgorithm_DPST4_5 
I/dispmgr (  318): DpstAlgorithm_DPST4_5 level is 3
I/art     ( 3431): Rejecting re-init on previously-failed class java.lang.Class<org.apache.commons.a.r>
D/Vpn     (  766): setting state=CONNECTING, reason=establish
E/org.pacien.tincapp.service.TincVpnService.a( 3431): Invalid network configuration:
E/org.pacien.tincapp.service.TincVpnService.a( 3431): 
E/org.pacien.tincapp.service.TincVpnService.a( 3431): At least one address must be specified
E/org.pacien.tincapp.service.TincVpnService.a( 3431): java.lang.IllegalArgumentException: At least one address must be specified
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.os.Parcel.readException(Parcel.java:1544)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.os.Parcel.readException(Parcel.java:1493)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1716)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.net.VpnService$Builder.establish(VpnService.java:686)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at org.pacien.tincapp.service.TincVpnService.b(Unknown Source)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at org.pacien.tincapp.service.TincVpnService.onStartCommand(Unknown Source)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2891)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.app.ActivityThread.access$2100(ActivityThread.java:147)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.os.Handler.dispatchMessage(Handler.java:102)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.os.Looper.loop(Looper.java:135)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at android.app.ActivityThread.main(ActivityThread.java:5264)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at java.lang.reflect.Method.invoke(Native Method)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at java.lang.reflect.Method.invoke(Method.java:372)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
E/org.pacien.tincapp.service.TincVpnService.a( 3431):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by pacien** [comment]
Hello, did you assigned an IP address either in the invitation file, or manually in the `network.conf` file on your device?

**Comment by kokoko3k** [comment]
Nope, i did not edited any invitation file, should i?
Also, my network.conf is zero sized.

**Comment by gappleto97** [comment]
It would be nice if you could add an address in the UI config generator, since invitation files aren't supported on most distros' tinc version.

**Comment by pacien** [comment]
Hello @gappleto97 and thank you for your suggestion. However, I would like to avoid adding UI fields for generating and editing configuration files. I think that editing the `network.conf` file is sufficient, and actually needed for a full configuration (with an address and routes at least).
