### ISSUE TITLE
Fatar error in NetworkListFragment on app start

### ISSUE THREAD

**Issue by pacien** [pacien/tincapp#71]
```
15:25:27.832 [main] INFO  org.pacien.tincapp.context.App - Starting tinc
app 0.20 (release build), running on REL (8.0.0)
15:25:28.429 [main] ERROR org.pacien.tincapp.context.App - Fatal
application error.
java.lang.IllegalStateException: start_network_list_placeholder_text must
not be null
at
org.pacien.tincapp.activities.start.NetworkListFragment$updatePlaceholder$1.run(NetworkListFragment.kt:81)
~[na:0.0]
at android.os.Handler.handleCallback(Handler.java:789) ~[na:0.0]
at android.os.Handler.dispatchMessage(Handler.java:98) ~[na:0.0]
at android.os.Looper.loop(Looper.java:164) ~[na:0.0]
at android.app.ActivityThread.main(ActivityThread.java:6944) ~[na:0.0]
at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
~[na:0.0]
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) ~[na:0.0]
15:25:31.994 [main] INFO  org.pacien.tincapp.context.App - Starting tinc
app 0.20 (release build), running on REL (8.0.0)
```

in https://github.com/pacien/tincapp/blob/v0.20/app/src/main/java/org/pacien/tincapp/activities/start/NetworkListFragment.kt#L81

**Comment by pacien** [comment]
Fixed with commit 31b4195.
