### ISSUE TITLE
Fatal application error

### ISSUE THREAD

**Issue by pacien** [pacien/tincapp#72]
```
14:25:56.976 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter list
	at org.pacien.tincapp.activities.status.networkinfo.VpnInterfaceConfigurationFormatter.formatList(VpnInterfaceConfigurationFormatter.kt) ~[na:0.0]
	at org.pacien.tincapp.databinding.StatusNetworkInfoFragmentBinding.executeBindings(StatusNetworkInfoFragmentBinding.java:191) ~[na:0.0]
	at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:437) ~[na:0.0]
	at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:409) ~[na:0.0]
	at android.databinding.ViewDataBinding$7.run(ViewDataBinding.java:194) ~[na:0.0]
	at android.databinding.ViewDataBinding$8.doFrame(ViewDataBinding.java:286) ~[na:0.0]
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765) ~[na:0.0]
	at android.view.Choreographer.doCallbacks(Choreographer.java:580) ~[na:0.0]
	at android.view.Choreographer.doFrame(Choreographer.java:549) ~[na:0.0]
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:739) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:211) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5389) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) ~[na:0.0]
```

**Comment by pacien** [comment]
Fixed with commit c9b813a.
