### ISSUE TITLE
Fatal application error

### ISSUE THREAD

**Issue by g3n35i5** [pacien/tincapp#85]
Hello @pacien , I'm afraid I'll soon be a regular in the issue section... After installing v0.26 and adjusting the configuration file I get the following error message when connecting to my network

```bash
09:21:14.183 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.26 (release build), running on REL (9)
09:21:19.105 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.AbstractMethodError: abstract method "java.lang.Object org.apache.commons.configuration2.builder.FileBasedBuilderProperties.setFile(java.io.File)"
	... 31 common frames omitted
Wrapped by: java.lang.reflect.InvocationTargetException: null
	at java.lang.reflect.Method.invoke(Native Method)
	at org.apache.commons.configuration2.builder.fluent.Parameters$ParametersIfcInvocationHandler.invoke(Parameters.java:349)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	... 28 common frames omitted
Wrapped by: java.lang.reflect.UndeclaredThrowableException: null
	at $Proxy0.setFile(Unknown Source)
	at org.apache.commons.configuration2.builder.fluent.Configurations.fileParams(Configurations.java:614)
	at org.apache.commons.configuration2.builder.fluent.Configurations.fileBasedBuilder(Configurations.java:132)
	at org.apache.commons.configuration2.builder.fluent.Configurations.propertiesBuilder(Configurations.java:238)
	at org.apache.commons.configuration2.builder.fluent.Configurations.properties(Configurations.java:282)
	at org.pacien.tincapp.data.TincConfiguration$Companion.fromTincConfiguration(TincConfiguration.kt:36)
	at org.pacien.tincapp.commands.TincApp.listPrivateKeys(TincApp.kt:41)
	at org.pacien.tincapp.utils.TincKeyring.needsPassphrase(TincKeyring.kt:31)
	at org.pacien.tincapp.activities.start.ConnectionStarter.tryStart(ConnectionStarter.kt:50)
	at org.pacien.tincapp.activities.start.ConnectionStarter.tryStart$default(ConnectionStarter.kt:41)
	at org.pacien.tincapp.activities.start.StartActivity$initNetworkListFragment$1.invoke(StartActivity.kt:63)
	at org.pacien.tincapp.activities.start.StartActivity$initNetworkListFragment$1.invoke(StartActivity.kt:41)
	at org.pacien.tincapp.activities.start.NetworkListFragment.onItemClick(NetworkListFragment.kt:65)
	at org.pacien.tincapp.activities.start.NetworkListFragment.access$onItemClick(NetworkListFragment.kt:39)
	at org.pacien.tincapp.activities.start.NetworkListFragment$onViewCreated$1.invoke(NetworkListFragment.kt:59)
	at org.pacien.tincapp.activities.start.NetworkListFragment$onViewCreated$1.invoke(NetworkListFragment.kt:39)
	at org.pacien.tincapp.activities.start.NetworkListFragment$sam$android_widget_AdapterView_OnItemClickListener$0.onItemClick(Unknown Source:10)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
	at android.widget.AbsListView$3.run(AbsListView.java:4052)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

When migrating from v0.25 to v0.26, do I need to consider anything else?

I have only added and customized the following to my configuration

```ini
# Search domain(s) to associate to the DNS resolver(s)
#SearchDomain = mynet

# Applications allowed or disallowed to use the VPN connection
#AllowApplication = com.example.app
# or
#DisallowApplication = com.example.app

# Allow applications to bypass the VPN connection
#AllowBypass = false

# Automatic reconnection on network change
ReconnectOnNetworkChange = false
```

I have changed the setting "ReconnectOnNetworkChange" as described in #84.

**Comment by kartoffelheinz** [comment]
Argh, been hit with this too about an hour ago when the app updated automatically. Please fix asap, cannot use our internal applications from my mobile currently :(

**Comment by pacien** [comment]
It looks like the new R8 optimiser is a bit too aggressive and removed dependencies from the release APK.
This is now fixed with release v0.27. It's published on the website and being deployed through Google Play.
Sorry for the inconvenience.

**Comment by g3n35i5** [comment]
Thanks @pacien for fixing this so fast. Everything works as it should.

**Comment by kartoffelheinz** [comment]
Yes, same here, thank you very much for the quick fix - everything's back to normal. Only Google Play took almost 24h to offer me the update - but that's probably nothing you can do anything about.
