### ISSUE TITLE
Tinc App v0. 27 - App crash "The app encountered a fatal error" 

### ISSUE THREAD

**Issue by ammarraisafti** [pacien/tincapp#88]
# Actual behaviour
When I accidentally double-click on every feature available in the tool section, it shouldn't stop this application.

# Expected behaviour
This application suddenly stopped when I accidentally double-clicked on every feature available in the tools section.

# Step to reproduce
- Install and open the application. 

- Enter application settings. Then double click on each feature available in the tools section.

- Then you will find problems like I have experienced.  The problem is that this application suddenly stops.

# Information
- Device: Nubia n2 lite
- Android version: 8.1.0
- Application version: 0.27

# Recording of the bug
https://youtu.be/90fqpBXMnlA

# Log cat
<code>21:57:39.398 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
21:59:54.049 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: JoinNetworkToolDialogFragment{e56571 #3 JoinNetworkToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
21:59:57.368 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:00:06.293 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: JoinNetworkToolDialogFragment{f4841 #3 JoinNetworkToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22:00:17.613 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:00:22.052 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: GenerateConfigToolDialogFragment{ee4789f #2 GenerateConfigToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22:00:27.274 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:00:32.757 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: EncryptDecryptPrivateKeysToolDialogFragment{2a1c4dd #2 EncryptDecryptPrivateKeysToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22:00:45.275 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:08:46.181 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:08:50.327 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: GenerateConfigToolDialogFragment{bee1d8d #2 GenerateConfigToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22:08:52.743 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:08:57.580 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: JoinNetworkToolDialogFragment{9b2ab33 #2 JoinNetworkToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22:08:59.702 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:09:03.511 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: EncryptDecryptPrivateKeysToolDialogFragment{3f378f2 #2 EncryptDecryptPrivateKeysToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22:09:07.537 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:10:19.020 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:10:22.727 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: GenerateConfigToolDialogFragment{971bb42 #2 GenerateConfigToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22:10:24.706 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:10:28.985 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: JoinNetworkToolDialogFragment{9b2ab33 #2 JoinNetworkToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22:10:31.016 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
22:10:35.107 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: EncryptDecryptPrivateKeysToolDialogFragment{ab06b43 #2 EncryptDecryptPrivateKeysToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
22:10:37.056 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
23:03:38.803 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)
23:03:42.370 [main] ERROR org.pacien.tincapp.context.App - Fatal application error.
java.lang.IllegalStateException: Fragment already added: GenerateConfigToolDialogFragment{76ebe24 #2 GenerateConfigToolDialogFragment}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1891)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:760)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6550)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
23:03:43.969 [main] INFO  org.pacien.tincapp.context.App - Starting tinc app 0.27 (release build), running on REL (8.1.0)</code>

**Comment by pacien** [comment]
Unreproducible.
